name: CI

on:
  push:

jobs:
  alternative-template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run success
        run: exit 0
      - name: Send message to Telegram
        uses: ./
        if: always()
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT: ${{ secrets.TELEGRAM_TO }}
        with:
          commit_template: ./templates/commit.mustache
